import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {getUserData} from "@/http/get";
import {cookies} from "next/headers";
import {redirect} from "next/navigation";
import {NextRequest, NextResponse} from "next/server";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className={inter.className}>
        {children}
      </body>
    </html>
  );
}
